"""Add created at and updated timestampt column

Revision ID: 9cdd6a4dd36a
Revises: cc9f20d252b3
Create Date: 2023-10-19 23:47:22.311869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cdd6a4dd36a'
down_revision: Union[str, None] = 'cc9f20d252b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_data', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('scraped_data', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_data', 'updated_at')
    op.drop_column('scraped_data', 'created_at')
    # ### end Alembic commands ###
