"""Add metadata as json column

Revision ID: cc9f20d252b3
Revises: 3da57b57585b
Create Date: 2023-10-19 23:19:09.800394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc9f20d252b3'
down_revision: Union[str, None] = '3da57b57585b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_data', sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_data', 'metadata_json')
    # ### end Alembic commands ###
